-- 코드를 작성해주세요
SELECT II.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO AS II JOIN ITEM_TREE AS IT ON II.ITEM_ID = IT.ITEM_ID
WHERE PARENT_ITEM_ID IN 
(SELECT II.ITEM_ID FROM ITEM_INFO AS II JOIN ITEM_TREE AS IT ON II.ITEM_ID = IT.ITEM_ID WHERE RARITY = 'RARE')
ORDER BY II.ITEM_ID DESC