-- 코드를 작성해주세요
SELECT ID, GENOTYPE, (SELECT GENOTYPE FROM ECOLI_DATA AS ED2 WHERE ED1.PARENT_ID = ED2.ID) AS PARENT_GENOTYPE
FROM ECOLI_DATA AS ED1
WHERE ED1.PARENT_ID IS NOT NULL AND (ED1.GENOTYPE & (SELECT GENOTYPE FROM ECOLI_DATA AS ED2 WHERE ED1.PARENT_ID = ED2.ID)) = (SELECT GENOTYPE FROM ECOLI_DATA AS ED2 WHERE ED1.PARENT_ID = ED2.ID)
ORDER BY ID