-- 코드를 작성해주세요
# SELECT ID, GENOTYPE, (SELECT GENOTYPE FROM ECOLI_DATA AS ED2 WHERE ED1.PARENT_ID = ED2.ID) AS PARENT_GENOTYPE
# FROM ECOLI_DATA AS ED1
# WHERE ED1.PARENT_ID IS NOT NULL AND (ED1.GENOTYPE & (SELECT GENOTYPE FROM ECOLI_DATA AS ED2 WHERE ED1.PARENT_ID = ED2.ID)) = (SELECT GENOTYPE FROM ECOLI_DATA AS ED2 WHERE ED1.PARENT_ID = ED2.ID)
# ORDER BY ID

SELECT ED1.ID, ED1.GENOTYPE, ED2.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS ED1 JOIN ECOLI_DATA AS ED2 ON ED1.PARENT_ID = ED2.ID
WHERE ED2.GENOTYPE = ED1.GENOTYPE & ED2.GENOTYPE
ORDER BY ED1.ID 