# -- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
(SELECT MAX(SIZE_OF_COLONY)
 FROM ECOLI_DATA AS ED2
 WHERE YEAR(ED1.DIFFERENTIATION_DATE) = YEAR(ED2.DIFFERENTIATION_DATE)) - ED1.SIZE_OF_COLONY AS YEAR_DEV, ED1.ID 
FROM ECOLI_DATA AS ED1
ORDER BY YEAR, YEAR_DEV
